---
version: "3.7"
services:
  mycart-frontend:
    build:
      context: ./frontend
    image: rahulr111/mycart-frontend:5.0
    environment:
      BACKENDLB: mycart-backend
    ports:
      - "9000:80"
    volumes:
      - type: volume
        source: mycart-frontend-logvol
        target: /var/log
    depends_on:
      - mycart-backend
  mycart-frontend-logs:
    build:
      context: ./awslogs
    image: rahulr111/mycart-frontend-logs:5.0
    volumes:
      - type: volume
        source: mycart-frontend-logvol
        target: /mnt/log
        read_only: true
    depends_on:
          - mycart-frontend
  mycart-backend:
    build:
      context: ./backend
    image: rahulr111/mycart-backend:5.0
    volumes:
      - type: volume
        source: mycart-backend-logvol
        target: /var/log
  mycart-backend-logs:
    build:
      context: ./awslogs
    image: rahulr111/mycart-backend-logs:5.0
    volumes:
      - type: volume
        source: mycart-backend-logvol
        target: /mnt/log
        read_only: true
    depends_on:
          - mycart-backend
volumes:
  mycart-frontend-logvol:
  mycart-backend-logvol: