---
version: "3.7"
services:
  mycart-frontend:
    build:
      context: ./frontend
    image: rahulr111/mycart-frontend:6.0
    environment:
      BACKENDLB: mycart-backend
    ports:
      - "9000:80"
    volumes:
      - type: volume
        source: mycart-frontend-logvol
        target: /var/log
    depends_on:
      - mycart-backend
  mycart-backend:
    build:
      context: ./backend
    image: rahulr111/mycart-backend:6.0
    volumes:
      - type: volume
        source: mycart-backend-logvol
        target: /var/log
  myapp-db:
    image: mysql:5.7
    volumes:
      - type: volume
        source: myapp-db-vol
        target: /var/lib/mysql
volumes:
  mycart-frontend-logvol:
  mycart-backend-logvol:
  myapp-db-vol: