---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mycart-frontend
  namespace: mycart
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: mycart
      layer: frontend
  replicas: 2
  minReadySeconds: 5
  progressDeadlineSeconds: 300
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template: 
    metadata:
      labels:
        app: mycart
        layer: frontend
    spec:
      containers:
      - name: mycart-frontend-container
        image: BUILDTAG
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "500Mi"
          requests:
            cpu: "0.2"
            memory: "200Mi"
        env:
          - name: BACKENDLB
            value: backendapi